version: "3.8"

services:
    api:
        build: .
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - MONGODB_URI=mongodb://mongodb:27017/restaurant-api
        depends_on:
            - mongodb
        volumes:
            - jwt_secret:/usr/src/app/.jwt_secret
        networks:
            - restaurant-network

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - restaurant-network

volumes:
    mongodb_data:
    jwt_secret:

networks:
    restaurant-network:
        driver: bridge
